# Generated by Django 5.0.6 on 2024-07-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
