# Generated by Django 5.0.6 on 2024-07-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admindb',
        ),
        migrations.AlterModelTable(
            name='admindb',
            table='admindb',
        ),
    ]
